apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-server-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-server-api
  template:
    metadata:
      labels:
        app: flask-server-api
    spec:
      containers:
        - name: flask-server-api
          image: flask-server-api  # L'image Docker locale
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-server-service
spec:
  selector:
    app: flask-server-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
